import { ContentItem } from "../types"

export const MOCK_CONTENT_ITEMS: ContentItem[] = [
  {
    id: "content-001",
    title: "Unboxing de la colección de verano",
    influencer: {
      id: "inf-001",
      name: "Ana Martínez",
      handle: "@ana_lifestyle",
      image: "/placeholder.svg?height=40&width=40",
    },
    startDate: "2023-06-14",
    endDate: "2023-06-14",
    platform: "Instagram",
    type: "Reel",
    status: "completed",
    objectives: [
      {
        id: "obj-001",
        title: "Alcance",
        target: "250K",
        current: "320K",
        status: "completed",
        percentComplete: 100,
      },
      {
        id: "obj-002",
        title: "Engagement",
        target: "5.5%",
        current: "6.2%",
        status: "completed",
        percentComplete: 100,
      },
    ],
  },
  {
    id: "content-002",
    title: "Lookbook de outfits de playa",
    influencer: {
      id: "inf-002",
      name: "Laura Gómez",
      handle: "@laurafashion",
      image: "/placeholder.svg?height=40&width=40",
    },
    startDate: "2023-06-24",
    endDate: "2023-06-27",
    platform: "Instagram",
    type: "Carrusel",
    status: "completed",
    objectives: [
      {
        id: "obj-003",
        title: "Alcance",
        target: "180K",
        current: "190K",
        status: "completed",
        percentComplete: 100,
      },
      {
        id: "obj-004",
        title: "Clicks",
        target: "5K",
        current: "4.8K",
        status: "in-progress",
        percentComplete: 96,
      },
    ],
  },
  {
    id: "content-003",
    title: "Tutorial de estilismo con accesorios",
    influencer: {
      id: "inf-003",
      name: "Carlos Style",
      handle: "@carlos_style",
      image: "/placeholder.svg?height=40&width=40",
    },
    startDate: "2023-07-04",
    endDate: "2023-07-04",
    platform: "YouTube",
    type: "Video",
    status: "in-progress",
    objectives: [
      {
        id: "obj-005",
        title: "Visualizaciones",
        target: "100K",
        current: "65K",
        status: "in-progress",
        percentComplete: 65,
      },
      {
        id: "obj-006",
        title: "Tiempo de visualización promedio",
        target: "5 min",
        current: "4.2 min",
        status: "in-progress",
        percentComplete: 84,
      },
    ],
  },
  {
    id: "content-004",
    title: "Challenge #VeranoModaExpress",
    influencer: {
      id: "inf-004",
      name: "Miguel Trends",
      handle: "@miguel_trends",
      image: "/placeholder.svg?height=40&width=40",
    },
    startDate: "2023-07-14",
    endDate: "2023-07-21",
    platform: "Twitter",
    type: "Video",
    status: "in-progress",
    objectives: [
      {
        id: "obj-007",
        title: "Impresiones",
        target: "500K",
        current: "320K",
        status: "in-progress",
        percentComplete: 64,
      },
      {
        id: "obj-008",
        title: "Engagement",
        target: "8%",
        current: "5.2%",
        status: "in-progress",
        percentComplete: 65,
      },
    ],
  },
  {
    id: "content-005",
    title: "Haul de compras de temporada",
    influencer: {
      id: "inf-005",
      name: "Sofía Trends",
      handle: "@sofia_trends",
      image: "/placeholder.svg?height=40&width=40",
    },
    startDate: "2023-07-29",
    endDate: "2023-07-29",
    platform: "Instagram",
    type: "Reel",
    status: "pending",
    objectives: [
      {
        id: "obj-009",
        title: "Alcance",
        target: "220K",
        current: "0",
        status: "not-started",
        percentComplete: 0,
      },
      {
        id: "obj-010",
        title: "Engagement",
        target: "5.2%",
        current: "0%",
        status: "not-started",
        percentComplete: 0,
      },
    ],
  },
  {
    id: "content-006",
    title: "Sesión de fotos en la playa",
    influencer: {
      id: "inf-001",
      name: "Ana Martínez",
      handle: "@ana_lifestyle",
      image: "/placeholder.svg?height=40&width=40",
    },
    startDate: "2023-08-04",
    endDate: "2023-08-09",
    platform: "Instagram",
    type: "Post",
    status: "pending",
    objectives: [
      {
        id: "obj-011",
        title: "Alcance",
        target: "200K",
        current: "0",
        status: "not-started",
        percentComplete: 0,
      },
      {
        id: "obj-012",
        title: "Engagement",
        target: "5%",
        current: "0%",
        status: "not-started",
        percentComplete: 0,
      },
    ],
  },
  {
    id: "content-007",
    title: "Review de productos de verano",
    influencer: {
      id: "inf-002",
      name: "Laura Gómez",
      handle: "@laurafashion",
      image: "/placeholder.svg?height=40&width=40",
    },
    startDate: "2023-08-12",
    endDate: "2023-08-12",
    platform: "Instagram",
    type: "Stories",
    status: "pending",
    objectives: [
      {
        id: "obj-013",
        title: "Impresiones",
        target: "300K",
        current: "0",
        status: "not-started",
        percentComplete: 0,
      },
      {
        id: "obj-014",
        title: "Swipe-ups",
        target: "10K",
        current: "0",
        status: "not-started",
        percentComplete: 0,
      },
    ],
  },
  {
    id: "content-008",
    title: "Tendencias de moda otoño",
    influencer: {
      id: "inf-003",
      name: "Carlos Style",
      handle: "@carlos_style",
      image: "/placeholder.svg?height=40&width=40",
    },
    startDate: "2023-08-18",
    endDate: "2023-08-18",
    platform: "YouTube",
    type: "Video",
    status: "pending",
    objectives: [
      {
        id: "obj-015",
        title: "Visualizaciones",
        target: "150K",
        current: "0",
        status: "not-started",
        percentComplete: 0,
      },
      {
        id: "obj-016",
        title: "Suscripciones",
        target: "2K",
        current: "0",
        status: "not-started",
        percentComplete: 0,
      },
    ],
  },
]

export const GANTT_CONFIG = {
  startDate: new Date("2023-06-14"),
  endDate: new Date("2023-08-20"),
  columnWidth: 60,
  stickyColumnWidth: 250,
} as const 